"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

CHECKLIST BEFORE COMMITTING AN AUTOGENERATED MIGRATION
------------------------------------------------------
Autogenerate is a first draft, not a finished migration. Always read it, and
check:

1. Does `downgrade()` actually reverse `upgrade()`? Autogenerate often gets this
   wrong or leaves it empty. An irreversible migration means an irreversible
   deploy.
2. Is any new NOT NULL column on an existing table given a `server_default`, or
   backfilled? Otherwise it fails the moment the table has rows.
3. Does an index on a large table use `postgresql_concurrently=True`? A plain
   CREATE INDEX takes an exclusive lock for its duration — minutes of downtime on
   a big table. (Concurrent index creation cannot run inside a transaction; see
   migrations/README.md.)
4. Was a column rename emitted as drop + add? That destroys the data. Replace it
   with `op.alter_column(..., new_column_name=...)`.
5. Are constraint names present and explicit? They should be, thanks to
   `naming_convention` in app/shared/db/base.py — if one is missing, that is a
   signal something bypassed the declarative base.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
${imports if imports else ""}

revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
