"""Initial schema: users, food_items, donations, notifications.

Revision ID: 0001
Revises: None
Create Date: 2026-07-29

WHY THIS MIGRATION IS HANDWRITTEN RATHER THAN AUTOGENERATED
-----------------------------------------------------------
Autogenerate would produce something close to this, but:

* it emits tables in an arbitrary order, which fails when a foreign key precedes
  its target;
* it does not create the `pgcrypto` extension that `gen_random_uuid()` needs;
* it produces an empty or wrong `downgrade()` more often than not;
* partial indexes (`postgresql_where`) are frequently mis-rendered.

The first migration establishes the shape of the whole schema, so it is worth
writing deliberately. Subsequent ones can start from autogenerate — with the
checklist in `script.py.mako` applied.

TABLE ORDER MATTERS: users -> food_items -> donations -> notifications. Each
references the ones before it. `downgrade()` drops them in exactly the reverse
order, which is the property that makes the rollback work.

WHY THIS IS PLAIN SQL AND NOT `op.create_table` / `sa.CheckConstraint`
-----------------------------------------------------------------------
Every statement below is executed verbatim through `op.execute(...)`, exactly
like `0002_seed_admin.py` does for its `INSERT`. No `sa.Column`, no
`op.create_index`, no SQLAlchemy construct that generates DDL on our behalf.

The reason is the same reason migrations use raw SQL for data changes: what
runs against the database should be readable *as SQL*, by anyone who knows SQL
and nothing about this project's Python layer or Alembic's operation API. A
`CREATE TABLE` statement is unambiguous and copy-pasteable into `psql` to
inspect or debug; `sa.Column("id", sa.UUID(as_uuid=True), ...)` is not — it is
one more translation step between what you read and what actually runs.

Because there is no `naming_convention` translation happening here (that only
applies to SQLAlchemy Table/Constraint objects), every constraint is named in
full directly in the SQL (`CONSTRAINT ck_users_role_valid CHECK (...)`, not a
short `role_valid` needing convention expansion). These names still match
`app/shared/db/base.py`'s `NAMING_CONVENTION`, which is what keeps
`alembic revision --autogenerate` from proposing a no-op rename against the
ORM models the next time it runs.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `gen_random_uuid()` lives in pgcrypto on PostgreSQL < 13 and is built in from
    # 13 onward. Creating the extension is idempotent and harmless on newer
    # versions, and it is what makes the `DEFAULT` on every id column work for rows
    # inserted by raw SQL or by a data migration.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ---------------------------------------------------------------- users
    op.execute(
        """
        CREATE TABLE users (
            id UUID NOT NULL DEFAULT gen_random_uuid(),
            -- 320 = RFC 5321 maximum (64-char local part + "@" + 255-char domain).
            email VARCHAR(320) NOT NULL,
            hashed_password VARCHAR(255) NOT NULL,
            full_name VARCHAR(255) NOT NULL,
            role VARCHAR(16) NOT NULL DEFAULT 'DONOR',
            is_active BOOLEAN NOT NULL DEFAULT true,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_users PRIMARY KEY (id),
            -- A CHECK constraint rather than a native Postgres ENUM: adding a value
            -- to an enum type is an awkward, hard-to-reverse migration, whereas
            -- editing a CHECK is a two-line reversible ALTER.
            -- See app/modules/users/models.py.
            CONSTRAINT ck_users_role_valid CHECK (role IN ('DONOR', 'RECIPIENT', 'ADMIN'))
        )
        """
    )
    # UNIQUE index rather than a UNIQUE constraint: functionally equivalent in
    # Postgres, but an index can later be rebuilt CONCURRENTLY without downtime.
    op.execute("CREATE UNIQUE INDEX ix_users_email ON users (email)")
    op.execute("CREATE INDEX ix_users_role ON users (role)")
    # Partial index — admin screens only ever list enabled accounts, so indexing
    # deactivated ones is pure write overhead.
    op.execute("CREATE INDEX ix_users_role_active ON users (role) WHERE is_active")

    # ----------------------------------------------------------- food_items
    op.execute(
        """
        CREATE TABLE food_items (
            id UUID NOT NULL DEFAULT gen_random_uuid(),
            name VARCHAR(255) NOT NULL,
            description VARCHAR(1000),
            -- NUMERIC, not DOUBLE PRECISION: quantities are summed for impact
            -- reporting, and binary floating point accumulates error. See models.py.
            quantity NUMERIC(10, 3) NOT NULL,
            unit VARCHAR(16) NOT NULL,
            expires_at TIMESTAMPTZ NOT NULL,
            status VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE',
            pickup_location VARCHAR(500) NOT NULL,
            owner_id UUID NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            is_deleted BOOLEAN NOT NULL DEFAULT false,
            deleted_at TIMESTAMPTZ,
            CONSTRAINT pk_food_items PRIMARY KEY (id),
            -- RESTRICT, not CASCADE: deleting a user must never silently erase the
            -- food they donated, because a Donation row records a real handover.
            CONSTRAINT fk_food_items_owner_id_users FOREIGN KEY (owner_id)
                REFERENCES users (id) ON DELETE RESTRICT,
            -- Enforced in the database as well as in Pydantic — defence in depth
            -- against a bad data migration or a manual UPDATE.
            CONSTRAINT ck_food_items_quantity_positive CHECK (quantity > 0),
            CONSTRAINT ck_food_items_status_valid
                CHECK (status IN ('AVAILABLE', 'RESERVED', 'DONATED', 'CANCELLED', 'EXPIRED')),
            CONSTRAINT ck_food_items_unit_valid
                CHECK (unit IN ('KG', 'G', 'L', 'PIECE', 'PORTION'))
        )
        """
    )
    op.execute("CREATE INDEX ix_food_items_owner_id ON food_items (owner_id)")
    op.execute("CREATE INDEX ix_food_items_expires_at ON food_items (expires_at)")
    op.execute("CREATE INDEX ix_food_items_is_deleted ON food_items (is_deleted)")
    # Composite, and the column order is the point: with owner_id leftmost this also
    # serves queries filtering on owner_id alone (leftmost-prefix rule).
    op.execute(
        "CREATE INDEX ix_food_items_owner_id_status ON food_items (owner_id, status)"
    )
    # The hottest read in the application (GET /food-items). Partial, so it stays
    # small even as DONATED rows accumulate forever.
    op.execute(
        """
        CREATE INDEX ix_food_items_available_expires ON food_items (expires_at)
        WHERE status = 'AVAILABLE' AND is_deleted = false
        """
    )

    # ------------------------------------------------------------ donations
    op.execute(
        """
        CREATE TABLE donations (
            id UUID NOT NULL DEFAULT gen_random_uuid(),
            food_item_id UUID NOT NULL,
            recipient_id UUID NOT NULL,
            status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
            note VARCHAR(1000),
            decline_reason VARCHAR(500),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_donations PRIMARY KEY (id),
            CONSTRAINT fk_donations_food_item_id_food_items FOREIGN KEY (food_item_id)
                REFERENCES food_items (id) ON DELETE RESTRICT,
            CONSTRAINT fk_donations_recipient_id_users FOREIGN KEY (recipient_id)
                REFERENCES users (id) ON DELETE RESTRICT,
            CONSTRAINT ck_donations_status_valid
                CHECK (status IN ('PENDING', 'ACCEPTED', 'COMPLETED', 'CANCELLED'))
        )
        """
    )
    op.execute("CREATE INDEX ix_donations_food_item_id ON donations (food_item_id)")
    op.execute("CREATE INDEX ix_donations_recipient_id ON donations (recipient_id)")
    # Two composite indexes, because the two main screens filter on different
    # leading columns — one index cannot serve both.
    op.execute(
        "CREATE INDEX ix_donations_recipient_id_status ON donations (recipient_id, status)"
    )
    op.execute(
        "CREATE INDEX ix_donations_food_item_id_status ON donations (food_item_id, status)"
    )
    # NOTE: deliberately NO partial unique index on (food_item_id) WHERE
    # status = 'PENDING'. Double-reservation is prevented by SELECT ... FOR UPDATE
    # in FoodItemService.reserve, which yields a clean 409 instead of an
    # IntegrityError far from its cause. See app/modules/donations/models.py.

    # -------------------------------------------------------- notifications
    op.execute(
        """
        CREATE TABLE notifications (
            id UUID NOT NULL DEFAULT gen_random_uuid(),
            user_id UUID NOT NULL,
            type VARCHAR(32) NOT NULL,
            title VARCHAR(255) NOT NULL,
            body VARCHAR(1000) NOT NULL,
            -- No FK: a notification is a historical record and must survive the
            -- donation it refers to being purged. See models.py.
            related_donation_id UUID,
            read_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_notifications PRIMARY KEY (id),
            -- CASCADE here, unlike the RESTRICT above: a notification is meaningless
            -- without its recipient and references no third party.
            CONSTRAINT fk_notifications_user_id_users FOREIGN KEY (user_id)
                REFERENCES users (id) ON DELETE CASCADE,
            CONSTRAINT ck_notifications_type_valid CHECK (
                type IN ('DONATION_REQUESTED', 'DONATION_ACCEPTED', 'DONATION_DECLINED',
                         'DONATION_COMPLETED', 'DONATION_CANCELLED', 'FOOD_EXPIRING_SOON')
            )
        )
        """
    )
    op.execute("CREATE INDEX ix_notifications_user_id ON notifications (user_id)")
    op.execute(
        "CREATE INDEX ix_notifications_user_id_created_at ON notifications (user_id, created_at)"
    )
    # The highest-value index in the schema: the unread badge is polled constantly,
    # while read notifications accumulate indefinitely. Partial on read_at IS NULL,
    # so its size tracks the backlog rather than all of history.
    op.execute(
        "CREATE INDEX ix_notifications_user_unread ON notifications (user_id) WHERE read_at IS NULL"
    )


def downgrade() -> None:
    """Reverse `upgrade()` exactly.

    Reverse dependency order — notifications, donations, food_items, users — because
    a table cannot be dropped while another still references it.

    `DROP TABLE` removes the table's own indexes and constraints, so they are not
    dropped individually. The `pgcrypto` extension is left in place: other schemas in
    the same database may rely on it, and dropping a shared extension during a
    rollback is how a rollback becomes an incident.
    """
    op.execute("DROP TABLE notifications")
    op.execute("DROP TABLE donations")
    op.execute("DROP TABLE food_items")
    op.execute("DROP TABLE users")
